spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

cloud:
  aws:
    credentials:
      access-key: test
      secret-key: test
    region:
      static: ap-northeast-2
    s3:
      endpoint: "https://test.compat.objectstorage.ap-northeast-2.oraclecloud.com"
    stack:
      auto: false

app:
  s3:
    bucket: test-bucket